{% set name = "koopa-viz" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/koopa-viz-{{ version }}.tar.gz
  sha256: 8d99053761205862acaabe96ab719d5e26bd6e33c1d4ec51ca37e6eb4150c470

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - napari
    - numpy
    - pandas
    - pyarrow
    - python >=3.8
    - qtpy
    - scikit-image
    - tifffile
    - trackpy

test:
  imports:
    - koopa_viz
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bbquercus/koopa-viz
  summary: Vizualization plugin for koopa image analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
