{% set name = "koopa-viz" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b2e73f4f81c156aaab418b950bc043fc8ba4332775a13132a8f5818ee1e92bd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - napari
    - numpy
    - pandas
    - pyarrow
    - python >=3.8
    - qtpy
    - scikit-image
    - tifffile
    - trackpy

test:
  imports:
    - koopa_viz
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bbquercus/koopa-viz
  summary: Vizualization plugin for koopa image analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
